### ISSUE TITLE
handle multiple callbacks in same blockonomics account 

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#1]
Use match_callback parameter

**Comment by blockonomics** [comment]
fixed in 9b4aaca

**Comment by comfortpay** [comment]
How exactly do you use this parameter?

do you have to place that in merchants --> HTTP Callback URL

and then something like: match_callback parameter=calbackurl_1&callbackurl_2

**Comment by shivaenigma** [comment]
Hi,

Could you please ping me on slack sometime, wanted to have a chat.

Regards,

**Comment by comfortpay** [comment]
Hi,

Yeah sure I will check right away. I will see if I can activate a notification or somethin as I don’t daily check the slack channel.

cheers

Robin
