### ISSUE TITLE
checkout intermittently not working

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#124]
- Gives unable to generate address
- I experienced this sometimes and one customer complained.

This looks like a timeout issue when doing new_address call. Check timeout parameter for wp_post and increase the value

**Comment by blockonomics** [comment]
- Lets reproduce this issue first by decreasing the timeout of _wp_remote_post_
- If able to reproduce then to fix... we can increase timeout to 10s

**Comment by DarrenWestwood** [comment]
The error is reproducible with the timeout set to 1s

**Comment by blockonomics** [comment]
- Ok looks like server is sometime busy and may not respond. 
- Default timeout is 5sec (should be enough), still lets increase to new_address call timeout to 8sec
