### ISSUE TITLE
Lite Mode Automation

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#137]
## Apply Lite automatically
- Detect theme during test setup / first time plugin install and set Lite Mode if it is any of our known conflicting themes.  We should not overwrite any existing lite_mode value set by user(true/false)
- Problem: We could be too conservative for some themes or miss out on some themes

## Detect payment page problems
- When payment page doesn't render, we somehow detect this and display error on Payment Page - _Unable to render correctly, Note to Administrator: Please enable lite mode in Blockonomics plugin_

**Comment by blockonomics** [comment]
Added two solutions. We may implement one of them or both depending on feasibility. Please check what is doable

**Comment by DarrenWestwood** [comment]
Both solutions are valid as can be seen in https://github.com/blockonomics/woocommerce-plugin/pull/138
