### ISSUE TITLE
Add BTC amount sent into "custom fields"

### ISSUE THREAD

**Issue by astupidmoose** [blockonomics/woocommerce-plugin#14]
Currently "blockonomics_address" and "blockonomics_txid" are both passed into the plugin as custom fields. 

I suggest adding the BTC amount in a separate field, "blockonomics_btcvalue" or something similar. 

This is useful for reporting and exporting of orders into accounting software. Currently, when downloading a report of the orders, BTC value is unknown and must be entered manually. I think it makes sense to have this piece of information along with the TX and Address fields, especially if addresses are reused ever.

**Comment by blockonomics** [comment]
This totally makes sense. Scheduled to be added in next release

>especially if addresses are reused ever.
Side point, addresses are never reused. Every one is a unique one.

**Comment by astupidmoose** [comment]
To further this point, We should be able to see the amount of BTC which was generated to be paid for the order, but also if there is an underpayment is it possible to add the "Amount Paid" as well? 

Currently, Underpayments are marked as such in the plugin but there is no way of knowing how much the customer was supposed to pay, and how much they did pay. 

Example Scenario: 
- Customer generates invoice and should pay 0.02588802 BTC
- Customer pays only 0.02548802 BTC (0.004 short, possibly withdrawal fees from an exchange)
- Payment of 0.02548802 goes to shops wallet. 
- Woocommerce marks payment as Failed (Underpayment). 
- Shop owner now sees a payment to his wallet, sees an underpaid order, but has no way of knowing what the difference between amount owed and amount paid is.

**Comment by blockonomics** [comment]
The *Amount Paid* can be directly found out by checking the payment address in blockonomics. I agree, it would be good to have this as well and to show the exact reason of payment failure.

**Comment by blockonomics** [comment]
Fixed in 73c84d4c599af63b2c55dc37f3770cf13aff2d69

**Comment by blockonomics** [comment]
Changes pushed plugin version 1.3.7
