### ISSUE TITLE
Debug Mode Warnings

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/woocommerce-plugin#140]
Turn on Debug mode and check warnings in various places:

- Checkout
  - Try normal / altcoin checkout
  - Altcoin Refund Screen
- Settings
 - Try Saving/Toggling each option
- Test Setup Cases
  - Successful test setup
  - Xpub not present
  - Incorrect callback
  - Account disabled

**Comment by shivaenigma** [comment]
From https://wordpress.org/support/topic/not-working-please-help-12/

`order_key was called incorrectly. Order properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-includes/template-loader.php’), do_action(‘template_redirect’), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action(‘wc_ajax_checkout’), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, `WC_Checkout->process_order_payment, WC_Gateway_Blockonomics->process_payment, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.`

I was also able to reproduce this in [Order Details](https://prnt.sc/ok92at)

**Comment by DarrenWestwood** [comment]
* Checkout
  * Try normal / altcoin checkout - No errors
  * Altcoin Refund Screen - No errors
* Settings - No errors
* Try Saving/Toggling each option - No errors
* Test Setup Cases
  * Successful test setup - ```Notice: Undefined property: stdClass::$message in /var/www/html/wpspeedtest/wp-content/plugins/blockonomics-bitcoin-payments/php/Blockonomics.php on line 49```
  * Xpub not present - ```Notice: Undefined offset: 0 in /var/www/html/wpspeedtest/wp-content/plugins/blockonomics-bitcoin-payments/php/Blockonomics.php on line 174```
```Notice: Trying to get property 'callback' of non-object in /var/www/html/wpspeedtest/wp-content/plugins/blockonomics-bitcoin-payments/php/Blockonomics.php on line 174```
```Notice: Undefined index: settings-updated in /var/www/html/wpspeedtest/wp-content/plugins/blockonomics-bitcoin-payments/blockonomics-woocommerce.php on line 133```
  * Incorrect callback - ```Notice: Undefined index: settings-updated in /var/www/html/wpspeedtest/wp-content/plugins/blockonomics-bitcoin-payments/blockonomics-woocommerce.php on line 133```
  * Account disabled - ```Notice: Undefined index: settings-updated in /var/www/html/wpspeedtest/wp-content/plugins/blockonomics-bitcoin-payments/blockonomics-woocommerce.php on line 133```
```Notice: Undefined property: stdClass::$address in /var/www/html/wpspeedtest/wp-content/plugins/blockonomics-bitcoin-payments/php/Blockonomics.php on line 50```

**Comment by DarrenWestwood** [comment]
> From https://wordpress.org/support/topic/not-working-please-help-12/
> 
> `order_key was called incorrectly. Order properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-includes/template-loader.php’), do_action(‘template_redirect’), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action(‘wc_ajax_checkout’), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, `WC_Checkout->process_order_payment, WC_Gateway_Blockonomics->process_payment, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.`
> 
> I was also able to reproduce this in [Order Details](https://prnt.sc/ok92at)

Use `$order->get_order_key()` instead of `$order->order_key`

**Comment by blockonomics** [comment]
> From https://wordpress.org/support/topic/not-working-please-help-12/
> 
> `order_key was called incorrectly. Order properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-includes/template-loader.php’), do_action(‘template_redirect’), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action(‘wc_ajax_checkout’), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, `WC_Checkout->process_order_payment, WC_Gateway_Blockonomics->process_payment, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.`
> 
> I was also able to reproduce this in [Order Details](https://prnt.sc/ok92at)

This error is still happening in master branch. @DarrenWestwood  Please fix
