### ISSUE TITLE
[slow connections] Getting unable to generate address

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#150]
- Facing this frequently on slow 4g connections
- On try again it seems to work due to caching

**Comment by blockonomics** [comment]
This is a timeout issue due to slow server response and customer is gettting
`Server is blocking HTTP Connections message`

**Comment by blockonomics** [comment]
@DarrenWestwood Feel free to put your thoughts here about this.See if we can reproduce this on our setup, one customer reported this today.

**Comment by blockonomics** [comment]
some customers have reported that regenerating API key helps to fix this. But I doubt this is the correlated. It just works after a few tries I suppose

**Comment by DarrenWestwood** [comment]
This is due to the default wordpress timeout for requests of 5 seconds. This behaviour can be overridden using the following code, which changes the timeout to 30 seconds
```
// Setting a custom timeout value for cURL.
add_action('http_api_curl', 'bnomics_custom_curl_timeout', 9999, 1);
function bnomics_custom_curl_timeout( $handle ){
    curl_setopt( $handle, CURLOPT_CONNECTTIMEOUT, 30 );
    curl_setopt( $handle, CURLOPT_TIMEOUT, 30 );
}
// Setting custom timeout for the HTTP request
add_filter( 'http_request_timeout', 'bnomics_custom_http_request_timeout', 9999 );
function bnomics_custom_http_request_timeout( $timeout_value ) {
    return 30;
}
// Setting custom timeout in HTTP request args
add_filter('http_request_args', 'bnomics_custom_http_request_args', 9999, 1);
function bnomics_custom_http_request_args( $r ){
    $r['timeout'] = 30;
    return $r;
}
```
30 seconds will be too much for production.

**Comment by blockonomics** [comment]
>This is due to the default wordpress timeout for requests of 5 seconds

I thought we already changed timeout previously ?

**Comment by DarrenWestwood** [comment]
We have included the code to use our own specified timeout
https://github.com/blockonomics/woocommerce-plugin/blob/wp_remote_post-timeout/php/Blockonomics.php#L132

and we are setting the timeout for new addresses generation to 8 seconds
https://github.com/blockonomics/woocommerce-plugin/blob/wp_remote_post-timeout/php/Blockonomics.php#L43

This can possibly be increased further, however this should be sufficient.
