### ISSUE TITLE
zero  order amount  should get autopayed

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#152]
Sometimes order amount is zero due to discounts. In case customer attempts to pay, the module should do the following (without showing payment screen)
- Mark the Payment complete . 
- Send user to order confirmation page

**Comment by DaveSiebel** [comment]
The order amount can also be zero because of a trial of a subscription.

**Comment by DarrenWestwood** [comment]
> The order amount can also be zero because of a trial of a subscription.

Hi @DaveSiebel , could you supply further instructions on your woocommerce trial subscription setup as I am trying to reproduce this error?

**Comment by DaveSiebel** [comment]
Hello @DarrenWestwood, 
We are using the [woocommerce subscription plugin](https://woocommerce.com/products/woocommerce-subscriptions/). When a subscription has a free trial, the payment amout will be zero dollars, but you still need to complete the checkout. When selecting blockonomics as payment method you need to send zero dollar, what can't be done.

**Comment by DarrenWestwood** [comment]
@DaveSiebel 
From Wordpress Dashboard >Woocommerce > Settings > Subscriptions Tab, verify you have checked the _$0 Initial Checkout_ checkbox

![WooCommerce settings ‹ Wordpress — WordPress](https://user-images.githubusercontent.com/39666372/66011202-6a511d80-e4c2-11e9-81ea-0c98a5b205fe.png)

Please, could you let me know if the above steps correctly resolve this issue on your end?

**Comment by DaveSiebel** [comment]
I can't find this option. Which version plugin are you using?

**Comment by DarrenWestwood** [comment]
I am testing with the latest version 2.6.1.

![WooCommerce settings ‹ Wordpress — WordPress (1)](https://user-images.githubusercontent.com/39666372/66244389-70384000-e708-11e9-9422-40f2b738512b.png)
Scroll down
![WooCommerce settings ‹ Wordpress — WordPress (2)](https://user-images.githubusercontent.com/39666372/66244391-74645d80-e708-11e9-8cb6-bfd3ecfaaaaa.png)

**Comment by DarrenWestwood** [comment]
@DaveSiebel, Could you verify the above changes are working correctly for you as well?

We are assessing this option further for possible inclusion into a later release.
Thank you for this suggestion.

**Comment by DaveSiebel** [comment]
Hello,
We are using Woocommerce Subscription plugin version 2.4.7. This option is not available.

**Comment by DarrenWestwood** [comment]
Please, could you update the [woocommerce subscription](https://woocommerce.com/products/woocommerce-subscriptions/) plugin to a version later than [2.5.0](http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-subscriptions/changelog.txt) to confirm this resolves the issue for you?

**Comment by DarrenWestwood** [comment]
Hi @DaveSiebel  
Please, could you update us on whether you have resolved this so the issue can be closed?
