### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by djsnho** [blockonomics/woocommerce-plugin#153]
Hello, i used the plugin on a small website of mine and worked perfect. After that i decided to install the plugin to my another website. After the plugin activation, i cant complete checkout with any payment gateway, and after hitting the payment button i go to a screen which have the "new order email" i should receive on admin email.

Here is my debug.log:
[25-Sep-2019 17:30:44 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WC_Order::get_id() in /wp-content/plugins/blockonomics-bitcoin-payments/blockonomics-woocommerce.php:339
Stack trace:
#0 /wp-includes/class-wp-hook.php(288): nolo_bnomics_woocommerce_email_customer_details(Object(WC_Order))
#1 /wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /wp-content/plugins/woocommerce/templates/emails/admin-new-order.php(48): do_action('woocommerce_ema...', Object(WC_Order), true, false, Object(WC_Email_New_Order))
#4 /wp-content/plugins/woocommerce/includes/wc-core-functions.php(203): include('/home/topsaerz/...')
#5 /wp-content/plugins/woocommerce/includes/wc-core-functions.php(216): wc_get_template('emails/admin-ne...', Array, '', '')
#6 /wp-content/plugins/blockonomics-bitcoin-payments/blockonomics-woocommerce.php on line 339

**Comment by blockonomics** [comment]
Can you let me know the woocommerce and wordpress version

**Comment by djsnho** [comment]
WC Version: 2.6.14
WP Version: 4.9.11

it may not be compatible with older wc & wp version ?

**Comment by blockonomics** [comment]
Wordpress version looks ok. Is it possible for your to update WC version ?

**Comment by blockonomics** [comment]
@djsnho  just confirming , updating WC has fixed this ?

**Comment by djsnho** [comment]
yes, after updating WC it got fixed. Thank you for answering
