### ISSUE TITLE
Reuse same address on order expiry / order retry

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#157]
Sometimes customers are paying to older address which is creating problem. On order expiry if not paid, the same address can be resued

**Comment by blockonomics** [comment]
_Rough outline of new expiry page_ 

**Payment Expired**

If you already paid:
Order will automatically confirmed when we detect your payment. You can safely close this window 

If you have not already made the payment:
Click here to Try Again

**Comment by blockonomics** [comment]
Adding to further scope of this:

- On payment page if customer is going back and then `Pay with Bitcoin` again it is the generating new address. This is causing uncessary generation of addresses.


So we have various cases like this:
1. Pay with bitcoin:  For same order always show same address. Clicking back and then trying this again will then effectively refresh the timer and price
2. Altcoin Page expiry: Same behaviour as 1.
3. Refresh F5 on payment page: Should not reset timer. Should continue on timestamp before refersh

@DarrenWestwood  can further help with design of this

**Comment by blockonomics** [comment]
I think this can have a simple solution:

1. We need to just modify process_payment() not to generate new address for same order and just reuse same address
2. Altcoin expiry will automatically taken care by 1. When use click on *CLick here* we just trigger the browser back button via JS

**Comment by freefiona85** [comment]
That's doable, but that means click here would make the user go back and confirming the order again - would the order number saved up? usually, when we click 'pay with bitcoin' after we go with back button after expiry, the order number will be changed...

**Comment by DarrenWestwood** [comment]
> We need to just modify process_payment() not to generate new address for same order and just reuse same address

`process_payment()` creates a new order everytime the `pay with bitcoin` button is clicked. We will not easily be able to change this as it is woocommerce behavior.
https://github.com/blockonomics/woocommerce-plugin/blob/master/php/WC_Gateway_Blockonomics.php#L95

I think it would be best if we add a check before [this](https://github.com/blockonomics/woocommerce-plugin/blob/master/php/WC_Gateway_Blockonomics.php#L160), to check if the order is expired or not based on the timestamp in the database. We can then update the expected price and new timestamp. 
This way, new info is only regenerated if the order is expired. The click here button will simply refresh the page.

**Comment by blockonomics** [comment]
> That's doable, but that means click here would make the user go back and confirming the order again - would the order number saved up? usually, when we click 'pay with bitcoin' after we go with back button after expiry, the order number will be changed...

Strange it is give me same order number each time I go back. Can you verify this ?

**Comment by freefiona85** [comment]
Ok, order number is the same. just verified it. it will only make a different number if you change a detail.

**Comment by freefiona85** [comment]
OK, commit modified.
