### ISSUE TITLE
Order fails if Customer pays too much

### ISSUE THREAD

**Issue by astupidmoose** [blockonomics/woocommerce-plugin#16]
Noticed today, a customer paid too much for an order but this set the order to failed. 

Not sure that this is the right behaviour to have as the customer will get a failed notice upon payment being received. Perhaps simply putting it to processing with a note on the order about overpayment?

**Comment by blockonomics** [comment]
Apologies for late reply. Yes, unforunately the plugin just checks if amount matches or not. 
You are right, overpayment can be passed with a note. Scheduled to be fixed in next release

Thanks again for your valuable inputs. Keep them coming !

**Comment by blockonomics** [comment]
Fixed in release 1.3.9 https://github.com/blockonomics/woocommerce-plugin/releases/tag/1.3.9
