### ISSUE TITLE
Plugin conflict

### ISSUE THREAD

**Issue by DarrenWestwood** [blockonomics/woocommerce-plugin#168]
```Fatal error: Cannot redeclare plugin_activation() (previously declared in /public_html/wp-content/plugins/contact-form-7-mailchimp-extension/lib/tools.php:162) in /public_html/wp-content/plugins/blockonomics-bitcoin-payments/blockonomics-woocommerce.php on line 443```

`plugin_activation` requires a prefix to fix the issue with plugin conflict:
https://github.com/blockonomics/woocommerce-plugin/blob/master/blockonomics-woocommerce.php#L442

**Comment by blockonomics** [comment]
is it issue only present with mailchimp ?

**Comment by DarrenWestwood** [comment]
This issue is only present with contact form 7 mailchimp extension:
https://plugins.trac.wordpress.org/browser/contact-form-7-mailchimp-extension/trunk/lib/tools.php#L162

Any plugin that declares a function named `plugin_activation` will create this conflict.
