### ISSUE TITLE
Shapeshift Option should include "APIKEY" field

### ISSUE THREAD

**Issue by astupidmoose** [blockonomics/woocommerce-plugin#17]
Great Job on integrating shapeshift!

I feel the settings should include an "Shapeshift API Public Key" field. 

Currently, Shapeshift offers an API key for affiliates. This allows shop owners to collect a commission on all transactions by setting their own API key in this field. 

We would also need to have the format of the URL include '&apiKey=' + $shapeshiftkey in order to have the URL formatted correctly. I've manually added this to my plugin, but would be nice to do in settings. :)

**Comment by blockonomics** [comment]
>Great Job on integrating shapeshift!
Thanks , good to know its working well for you. 

An option  makes sense. We want people to safely update to newer versions of plugin without disturbing their settings. 0.25% is too low a commision though :smile_cat:

**Comment by blockonomics** [comment]
shapeshift wont be used anymore
