### ISSUE TITLE
JS still being loaded on NoJS version

### ISSUE THREAD

**Issue by DarrenWestwood** [blockonomics/woocommerce-plugin#188]
The JavaScript files are still being enqueued when the nojs template is being used:
https://github.com/blockonomics/woocommerce-plugin/blob/master/php/WC_Gateway_Blockonomics.php#L156

If the `$template` is `blockonomics_nojs_checkout.php` do not enqueue the blockonomics js

**Comment by shivaenigma** [comment]
Fixed in https://github.com/blockonomics/woocommerce-plugin/pull/187. Please verify
