### ISSUE TITLE
Transaction info not added to order info

### ISSUE THREAD

**Issue by DarrenWestwood** [blockonomics/woocommerce-plugin#209]
The plugin is no longer displaying the transaction link on customer invoices.
![Invoice](https://user-images.githubusercontent.com/39666372/92870952-b01da200-f404-11ea-8ca9-d2edadcd8d68.png)

This has not been updated for bch:
https://github.com/blockonomics/woocommerce-plugin/blob/master/blockonomics-woocommerce.php#L344-L361

**Comment by shivaenigma** [comment]
The issue is that post meta is now in different format

   update_post_meta($wc_order->get_id(), 'paid_'. $order['crypto'], $value/1.0e8);
