### ISSUE TITLE
Flyp.me support?

### ISSUE THREAD

**Issue by devnuvo** [blockonomics/woocommerce-plugin#219]
Is there any possibility to add Flyp.me support back to the plugin?

Right now only BTC and BCH is supported, we would like to have the Flyp.me support enabled so that customers can pay with Altcoins.

**Comment by shivaenigma** [comment]
There is no plan to add flypme. support back. The problem was  converting ETH to BTC  taking high bitcoin transaction fee. This negated the usefulness of accepting ETH.

We have plans to add native ETH support next year
