### ISSUE TITLE
2 WP plugins?

### ISSUE THREAD

**Issue by agarzon** [blockonomics/woocommerce-plugin#220]
I was installing my WP test environment when I notice there are two plugins named the same **Blockonomics** word

![image](https://user-images.githubusercontent.com/339828/98961474-97e50480-24d3-11eb-8132-acaf5a9b7565.png)

It is the same author? this could lead to confusion to newcomers.

**Comment by shivaenigma** [comment]
One is for easy digital downloads and other for woocoomerce. We haven't yet had any reports of newcomers getting confused :D. Anyway there is no harm in installing both.

**Comment by agarzon** [comment]
So being those two plugins part of Blockonomics I'll close this issue.
