### ISSUE TITLE
Use of __FILE__ to load JS/CSS is causing problems

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#228]
Steps to reproduce
- zip the source code directory checked out from to create plugin zip
- Delete existing plugin installation
- Install zip by uploading it
- Activate zip
- On checkout we get the following error:
![Screenshot from 2021-01-16 17-10-29](https://user-images.githubusercontent.com/22165583/104811167-be028a00-581f-11eb-8f83-7a95e9c92913.png)

**Comment by blockonomics** [comment]
Strangely direct zip from git is working. What is the reasons of using `__FILE__` instead of enqueue stylesheet. I could see it  causing problems in other complex VPS setups too. Why not use `get_stylesheet_directory_uri()`  and `wp_enqueue_style`

**Comment by DarrenWestwood** [comment]
I am unable to reproduce this error on my end. get_stylesheet_directory_uri is a function for themes and cannot be used in this case. 
Using plugins_url() is the recommended way to handle enqueue URLs in plugins.
