### ISSUE TITLE
Guide to edit locale string/translations

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/woocommerce-plugin#236]
There are common requests to [edit strings](https://www.reddit.com/r/blockonomics/comments/lm3xvs/anyway_to_change_payment_text/) or change the translation of string in a specific language.

This should be possible using [loco translate plugin](https://wordpress.org/plugins/loco-translate/). We need a guide for this which will be posted on our help portal

**Comment by cnohall** [comment]
I'll examine the loco translate plugin and then write a guide that customers can use to change or translate strings into what they find suitable

**Comment by cnohall** [comment]
Here's a [rough draft](https://docs.google.com/document/d/1E3_OofSwPg9HhBR1nI92NYnvel0RvU8hfYwF7XOsmwo/edit?usp=sharing) of the guide. I'll continue to work on it. Feel welcome to share any ideas on how to improve either the content or the format.

**Comment by cnohall** [comment]
Images have been added to the draft. There are two "schools of thought" when it comes to images. One like to show large images (including almost everything on the page. The other one likes to be more minimalistic and show only what's relevant. I opted for the larger images and using red squares to mark the relevant sections. Let me know if we should try the smaller image appoach.

**Comment by DarrenWestwood** [comment]
Closing this issue as the guide can be found here: https://help.blockonomics.co/support/solutions/articles/33000260804-wordpress-woocommerce-editing-or-translating-text
