### ISSUE TITLE
Refershing payment screen should reset timer and price

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/woocommerce-plugin#251]
If user sees the timer already at say 2 min, as he doesn't have time. He will do this:

1. Press back and go back to crypto selection screen or *Pay with  Bitcoin* Wordpress checkout screen
2. He hopes that a new checkout is created, when he comes back which doesn't happen and he is still at around 2 min
3. WHMCS currently works like this. Address can be resused as it same order number, however timer / price should be refreshed

**Comment by cnohall** [comment]
Sound good, looking forward to working on this!

**Comment by shivaenigma** [comment]
This is a complex issue and here are few reasons why we till now retain page values on refresh:

- Opening the same checkout in a new tab/multiple refreshes may lead to incorrect expected amounts
- Customer can send the link to another person to pay, in which case it is desirable they see the same amount
- Mobile will discard tab and reload it sometimes https://www.chromium.org/chromium-os/chromiumos-design-docs/tab-discarding-and-reloading

However, looking afresh from customer point of view, it is important this behaviour is changed:
- Problems when time [remaining is low](https://github.com/blockonomics/woocommerce-plugin/issues/251#issue-928445347)
- More importantly refresh should always **show the latest bitcoin price** as far as possible. This is fair to both the customer and the merchant. If customer enters the BTC amount in his wallet and the fiat amount is deviating a lot, it causes a problem

Following changes must be implemented:
- Refreshing crypto payment screen will reset time and update price if order is still hasn't received any tx. Address will of course be reused 
- Technical notion of *time_remaining* etc and other uncessary time variables on server/client side can be removed
