### ISSUE TITLE
Crypto Selection Screen Update

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/woocommerce-plugin#252]
If feel we can still improve the crypto selection a lot:

1. [Non clickable regions](https://drive.google.com/file/d/1GfMAoeG-E7gTL4QIBv7zBjhBQ7U1-rot/view?usp=sharing)
2. Improve look / feel further
3. Mobile usability must be good. Right now mobile is same as desktop which is wrong. Mobile should change to a [vertical layout](https://prnt.sc/16gwbt8)

**Comment by cnohall** [comment]
Sound good, looking forward to working on this!
