### ISSUE TITLE
NOJS checkout copy problems

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#255]
In noJS checkout copy to clipboard is not working. This is excepted however, now both the amount and address input should work like normal wordpress text input fields /labels . User should be able to select it via mouse by two clicks on the word

**Comment by cnohall** [comment]
I'm on it

**Comment by cnohall** [comment]
It seems like it's already possible? I tried it without doing any changes to the code. I also tried it on the mobile version, seems like a long tap is the way to go on mobile. 

![Animation](https://user-images.githubusercontent.com/36883813/124057318-3671a600-da62-11eb-8e6b-abdea99920cf.gif)

**Comment by blockonomics** [comment]
You haven't disabled JS ! Goto Settings > Blockonomics > Advanced Settings and disable JS

**Comment by cnohall** [comment]
I'm quite sure that I did. The left checkout screen is without JS and the on the right is with JS?
![image](https://user-images.githubusercontent.com/36883813/124092980-5f119400-da92-11eb-9032-8485c4e0257a.png)

**Comment by blockonomics** [comment]
Ok try in firefox. Looks like chrome it is working. Another thing is mouse cover should not be click (it is confusing).

Both the input fields should looks like wp-admin> settings> Blockonomics **API Key**

**Comment by cnohall** [comment]
By changing the cursor to `text` firefox (and the other broswers) understood that the text should be selectable, even in mobile mode.

![image](https://user-images.githubusercontent.com/36883813/124218058-6be6c400-db34-11eb-864c-c30d02dfefdb.png)
