### ISSUE TITLE
Malformed html of order page

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#26]
![screenshot from 2017-11-01 13-00-24](https://user-images.githubusercontent.com/22165583/32264444-9dfcaa0a-bed6-11e7-8cbf-5e54b89ac09e.png)

**Comment by aleangel1212** [comment]
Fixed: Can't have html tags inside of order page because it confuses the browser. The page title is defined by the theme, not the plugin.

**Comment by blockonomics** [comment]
fixed by #29
