### ISSUE TITLE
Php Error  - Test Setup / Update Callback

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#260]
- Make callback on server empty 
- Click on Test Setup, everything works
- However below is shown in console
![Screenshot from 2021-07-16 16-59-17](https://user-images.githubusercontent.com/22165583/125941033-dc4370cf-cfbf-4ded-b79e-9b872e2d5b21.png)

**Comment by cnohall** [comment]
Are you using an add-on to get the PHP Errors? 

I'm don't get the PHP Error section in my _Query Monitor_ submenu.
![image](https://user-images.githubusercontent.com/36883813/125945839-7be29d06-9c36-4af6-964f-23ec9221cfc9.png)
