### ISSUE TITLE
Remove URL redundancy in code

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#265]
Same endpoint reference is unnecessarily getting [repeated](https://github.com/blockonomics/woocommerce-plugin/blob/master/php/Blockonomics.php#L9). This also leads to redundancy [like this](https://github.com/blockonomics/woocommerce-plugin/blob/master/php/Blockonomics.php#L59)  

### Solution
Refactor code to remove redundancy like [in prestashop](https://github.com/blockonomics/prestashop-plugin/blob/1.7/blockonomics.php#L238)

**Comment by anktd** [comment]
We can close this
