### ISSUE TITLE
Set order status processing/completed

### ISSUE THREAD

**Issue by Undersidedog2** [blockonomics/woocommerce-plugin#27]
How to make that, to set automatically just paid transactions for order processing/completed on just uncofrmies transaction. Plugin needs 2 confirtmation to change status to completed or processing i want to make number of confirmations 0

**Comment by blockonomics** [comment]
You can change [this line](https://github.com/blockonomics/woocommerce-plugin/blob/1e2f87e732cc55f8e337fc70f630e0793d8f7bde/blockonomics-woocommerce.php#L244) to status==0
