### ISSUE TITLE
Support for divi theme / page builder themes 

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#281]
Currently we only support via lite mode. Also see issue #9 for previous work on this. Page builder themes have a huge market share so support for them should definitely be planned.

**Comment by blockonomics** [comment]
Adding @thisisayush  for research

**Comment by vinlim** [comment]
Consider using [custom web component](https://blockonomics.slack.com/archives/D05A3V7ETFF/p1691472832388079)
https://developer.mozilla.org/en-US/docs/Web/API/Web_componentsto resolve this by encapsulating the checkout component with Shadow DOM.

Customization can also be done with [CSS Custom Properties](https://web.dev/custom-properties-web-components/)

**Comment by shivaenigma** [comment]
Already addressed via custom post type see https://github.com/blockonomics/woocommerce-plugin/issues/9
