### ISSUE TITLE
Underpayment - Allow customer to pay more

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#282]
Currently on underpayment customer has no option than to wait for merchant. He can be given an invoice to pay the pending amount. Also we have think if underpayment slack will still work

**Comment by blockonomics** [comment]
Check woocommerce order actions . Merchant has option to accept order or send invoice to customer for more payment

**Comment by blockonomics** [comment]
The idea here is the following. On underpayment, the merchant should get following options to do on opening Woocommerce > Orders > Order Details

1. Show the received USD amount vs Order Amount clearly to the merchant. Eg 18USD was received for 20USD other
2. Merchant has two options:
   i. Accept the order
   ii. Invoice the customer for remaining 2USD 
3. Also indicate underpayment slack option to merchant avoid future problems

**Comment by ankit61d** [comment]
Sounds an interesting problem to work upon.

**Comment by ankit61d** [comment]
Order details after underpayment for an order (Merchant setting has 0% underpayment slack). 
Note that (i) it is marked as failed so it is no longer editable, and (ii) merchant can send "Note to Customer".

![2209-000792](https://user-images.githubusercontent.com/97018228/191675423-f21b72a5-08ea-42fb-9591-7e9b5d8be0df.jpg)




> Show the received USD amount vs Order Amount clearly to the merchant

We can add 2 more fields for this as seen here:
![2209-000793](https://user-images.githubusercontent.com/97018228/191672517-8494f53b-ea08-4574-8060-5ea96989ee42.jpg)

> i. Accept the order


For this merchant only need update the order status to "Completed":
<img width="413" alt="image" src="https://user-images.githubusercontent.com/97018228/191672909-d8dd70df-f012-4b93-8fa7-a2bbbe266fa7.png">

> ii. Invoice the customer for remaining 2USD. On receiving this we have to mark invoice paid

The first thing merchant has to do is change the status back to "Pending Payment" so as to make the order editable again. Now merchant can email invoice order details from order action. 
![2209-000800](https://user-images.githubusercontent.com/97018228/191682546-e6eadbdd-5b02-4841-8887-a4873f70ed7a.jpg)

Here is the email customer receives:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/97018228/191681539-cdf39097-fe42-4626-8d62-6eb8847880b8.png">

 The link in email will generate this payment page for customer:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/97018228/191680653-fe11b8c5-8d05-468d-8d58-99788f56ae88.png">

Now, currently when we click pay with bitcoin here, it takes to underpayment error page. 
<img width="517" alt="image" src="https://user-images.githubusercontent.com/97018228/191681019-22eec4f7-7c38-478b-ab57-ec6b879c95e2.png">

We can rethink how we handle the underpayment error. Here the remaining amount can be shown with a link to "Complete the checkout by paying remainder amount".



> Also indicate underpayment slack option to merchant avoid future problems

We should add a dedicated article on https://help.blockonomics.co/support/home regarding this. Currently we have this mentioned under [FAQ for our wordpress plugin](https://help.blockonomics.co/support/solutions/articles/33000248575-wordpress-woocommerce-integration-faq-).

**Comment by ankit61d** [comment]
[Here is doc](https://docs.google.com/document/d/1UVQs02Zv3EP1T_jviXuu7q3mVBKPQrr_eYiKBZrmz9E/edit?usp=sharing) about more on existing 'Underpayment' or 'Partial Payment' flows. 

**Conclusion**: I have made underpaid order to keep 'Pending Payment' status and showing checkout again for the same order. I also modified callback function for 2nd callback, it didn't work. This doc also mentions how other payment gateways are handling such payment flows. On Woocommerce, these flows already specify multiple payments before placing the order (ex. in multiple installments , or partly paid on delivery).

**Comment by shivaenigma** [comment]
Best is to move to Coupons

Here is the phasewise plans on how to move forward on this - Lets make tasks on asana

### Phase 1
- Research creating and applying automated coupons via woocommerce functions and later delete them ?
- Coupon is applied automatically on confirmed callback if it is an underpayment
- Refreshing Order checkout page now shows the updated partial amount to pay

### Phase 2
- Remove paid_btc and expected_btc custom fields. We will require new custom fields - paid_order_amount  . Note that the for remaining partial amount again, we need to generate new address, so one order will have multiple addresses and may require DB changes. Let visit how we are doing [this in whmcs](https://github.com/blockonomics/whmcs-bitcoin-plugin/pull/41/files) and then finalize DB structure 
- Partial payment callbacks are now working and all custom fields in woocomerce orders are updating properly

### Phase 3
- Checkout page auto refreshes on underpayment and show the following - Existing order amount paid is shown and a message is shown to explain what to do to avoid same error again
- Code refactoring, testing edge cases and release

**Comment by ankit61d** [comment]
**Update on Phase 1**: Using [WC_Coupon](https://woocommerce.github.io/code-reference/classes/WC-Coupon.html), I am able to create and apply a coupon to the order on underpaid callback, in [check_paid_amount](https://github.com/blockonomics/woocommerce-plugin/blob/master/php/Blockonomics.php#L748) function. For now I am using a hardcoded value instead of amount paid in the underpayment transaction. If the store currency is not btc, I need to convert the callback value to the store currency. So I need to store the conversion rate at time order was last updated. Or I can use remaining btc to paid and use that to get amount paid in fiat.
Here is such coupon applied after underpayment:
![0710-000817](https://user-images.githubusercontent.com/97018228/194468304-2dae6f91-1b27-4bd9-b372-27e8e5c932f4.jpg)
This is the customer payment page after coupon is applied:
![0710-000819](https://user-images.githubusercontent.com/97018228/194468954-749856cd-e265-4f2f-9d43-75ad8c230fb5.jpg)

For deleting coupon, we can use [set_usage_limit](https://woocommerce.github.io/code-reference/classes/WC-Coupon.html#method_set_usage_limit) to 1 and later [delete](https://woocommerce.github.io/code-reference/classes/WC-Coupon.html#method_delete) it.

**Comment by ankit61d** [comment]
Note: I have also tried [WC_Order_Item_Coupon](https://woocommerce.github.io/code-reference/classes/WC-Order-Item-Coupon.html) but it is not updating the cart total, as seen [here](https://stackoverflow.com/questions/53098617/applying-coupon-to-woocommerce-order-programmatically). I did try the solution given using `add_action` and another one given [here](https://stackoverflow.com/a/48190813) to apply coupon to each product in the order individually, but these didn't work.

**Comment by shivaenigma** [comment]
Closing as already addressed
