### ISSUE TITLE
Upgrade to more modular Checkout UX 

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#283]
![Property_1payment](https://user-images.githubusercontent.com/22165583/186842256-3279ebae-c7bd-400b-b261-17fbcffb4b30.png)
### Desired Behaviour/Motivation
- Timeout is confusing and it seems to customer that if he doesn't send within that time, his payment is lost
- If time reaches 2 min or so, customer is basically left with nothing to do as he knows he cannot complete payment in that time
- A modular UX clearly indicates that the timer is for price refresh and address stay the same

**Comment by blockonomics** [comment]
Lets start working on this for wordpress:
- Important thing is that we should respect the theme and not do unnecessary styling
- We have to think on how to implement boxes that gel with the theme (We cannot use background color)
- Mobile friendliness is important
- Copy we can the COPY component UX

**Todo for next version**
- Refresh now should only reload the BTC amount section instead of refreshing the entire page. Important that this should not be over-complicated

**Comment by blockonomics** [comment]
>Refresh now should only reload the BTC amount section instead of refreshing the entire page. Important that this should not be over-complicated
@thisisayush Lets think about this while you are waiting for design

**Comment by thisisayush** [comment]
I think this can be achieved by what we had previously, an AJAX API that can be used to refresh the order parameters and show it here. It'll not be possible in NoJS Solution, but we can implement auto page reload in NoJS Scenario as well (using HTML meta page refresh)

**Comment by blockonomics** [comment]
Yes in noJS we can just reload the page. That is not a problem
Lets see what minimalistic AJAX API we can use that other wordpress plugins are using using. Maybe jquery can be used as we know wordpress will have jquery
