### ISSUE TITLE
Make QR code generation work without GD extension

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#286]
`PHP Fatal error:  Uncaught Error: Call to undefined function ImageCreate() in /home/enigma/blockonomics-bitcoin-payments/php/phpqrcode.php:999`

https://stackoverflow.com/questions/3106991/fatal-error-call-to-undefined-function-imagecreate
We don't expect merchant to have GD extension as this is not a requirement for wordpress

**Comment by ankit61d** [comment]
I am on it.

**Comment by ankit61d** [comment]
There can be 2 possible solution here:

1. We can replace the current `php/phpqrcode.php` library with [this php svg qr generator](https://github.com/splitbrain/php-qrcode/blob/master/src/QRCode.php) and pass the qrcode_svg_element to the template.
2. We can simply use open api for QR code generation. [This is a google api for qr codes](https://developers.google.com/chart/infographics/docs/qr_codes) but it is deprecated. There are other qr code api like [this one](https://documentation.image-charts.com/qr-codes/) or [this one](https://quickchart.io/documentation/#qr).

Going with the first here as it seems more reliable.
