### ISSUE TITLE
internal server error when pressing on "place order" button

### ISSUE THREAD

**Issue by comfortpay** [blockonomics/woocommerce-plugin#3]
Hello,

I just installed your woocommerce plugin. All went well till i tried to do a test payment on my website. When i press the place order button i get a woocommerce message saying: internal server error. No futher error message is mentioned, thats all.

What i have done so far:
1 create a blockonomics account and followed all merchant steps
2 installed the plugin, added the api and callback url

test payment inside blockonomics is going fine.

I selected EUR as currency inside my blockonomics account, but that should not matter right? I will do some test and see if it makes a difference if i select usd in blockonomics account

**Comment by blockonomics** [comment]
Thanks for using our plugin. Yes the currency doesn't matter
Most probably the API key that you copied from blockonomics into woocommerce plugin isn't correct

For example in the snapshot the API key is only
```HwefKFBjDkl1EB5l8NvorH9G28jG3UZ7TwCM1hUIGIA```
![screenshot from 2017-03-19 09-03-37](https://cloud.githubusercontent.com/assets/22165583/24077908/203608f6-0c83-11e7-9203-756b4453062c.png)

Let me know if this fixes the issue.

**Comment by blockonomics** [comment]
@comfortpay did the above fix, resolve your issue ?

**Comment by comfortpay** [comment]
Not yet. im now busy installing it on some other websites to see if i ran into the same issues there. Once im done debugging and testing i let you know.

**Comment by comfortpay** [comment]
Hi,

Issue still not resolved. I tried to use the plugin on multiple sites, all with the internal server error as a result. No errors found in my server log files.

To fully make sure it wasnt another plugin conflict i installed wordpress on an empty domain and only activated woocommerce and blockonomics plugin. I also created a completely new account at blockchain.info and a new account at blockonomics.

Then i:
- completed the xpub step
- generated an api from wallet watcher --> settings and copied it wordpress settings --> blockonimics (api = NsJ4ru3xOGUKgSyGHaRrW5BtIpD2z1RMURculSxhTUE). I made sure there where no empty spaces or whatever.
- copied the callback url to merchants in blockonomics

Then tried to place and order but as soon as i press the "place order" button i get a "internal server" error.

Dont really know what else i can check, really seems a bug on your side.

Few things that i noticed:
1. when i visit your website i get an ssl certificate error, maybe that also cause the plugin to crash as i see the plugin uses https requests to your website.

2. a bit confusing is the various blockonomics plugins you offer. For example if i download the plugin from https://github.com/blockonomics/woocommerce-plugin the plugin folder that is downloaded is called "woocommerce-plugin-master".  But if i follow the readme text and download it from https://github.com/blockonomics/woocommerce-plugin/releases the plugin folder is called "blockonomics". And no matter which of the above i use, if i update one of those from within wordpress the plugin folder gets renamed to "blockonomics-bitcoin-payments". In order to get it to work again after an update i have to remove the old one and activate the new one which kinda sucks.

Bye the way, i tried all the different plugin folders and also tried both new as old versions. All end up in the same result, internal server error when i try to place the order.

**Comment by blockonomics** [comment]
HI,

- I have removed the API key from your comment for security
- I checked the server, your API request is not hitting our server. Seems like your webhost may be blocking outgoing HTTP requests
- Thanks for pointing the SSL issue. It has been fixed new newer version of plugin the wallet watcher url is https://www.blockonomics.co and not https://blockonomics.co. However, this is not the issue in your case
- Also noted that the folder issue is causing confusion. We will fix this

I have a sent you an invite to our slack channel. Our support engineer will help you fix the issue.

Thanks for taking out time to debug this. Looking forward to chatting with you on our slack channel

**Comment by comfortpay** [comment]
Hi,

I found out why it wasnt working. I noticed a PHP Parse error:  syntax error, unexpected '.', expecting ',' on line 6 in blockonomics.php

Seems in newer versions of php the below construct of base_url doesnt work correctly.

`   const BASE_URL = 'https://www.blockonomics.co';
    const NEW_ADDRESS_URL = Blockonomics::BASE_URL. '/api/new_address';
    const PRICE_URL = Blockonomics::BASE_URL.'/api/price';
`

As you only used the base_url for the new_Address_url and the price_url i changed it to:

`
    const BASE_URL = 'https://www.blockonomics.co';
    const NEW_ADDRESS_URL = 'https://www.blockonomics.co/api/new_address';
    const PRICE_URL = 'https://www.blockonomics.co/api/price';
`

I didnt delete the base_url line in this sample but i think that can be deleted fully.

Now the plugin works again.

**Comment by comfortpay** [comment]
Oh please check if my changes are ok, i didnt check any other files as the internal server error only applied to the blockonomics.php file, but as far as i can see this should be a valid fix

**Comment by comfortpay** [comment]
One more question:

i see the free version you get upto 50 addresses. How exactly is that calculated. Will a new address been generate on each pageload or will it only generate 1 address for each completed payment?

And how exactly does that work. You will generate a new address (customer sends funds to that address). Is that address generate in my blockchain.info account through the xpub key? Or am i seeing this wrong?

**Comment by blockonomics** [comment]
Thanks for finding the issue. Hi... lets chat on our slack channel. Lots to talk about. I sent you invite already. If you want me to send to different ID let me know

**Comment by blockonomics** [comment]
Hi... can you tell which php version this issue was coming

**Comment by comfortpay** [comment]
Hi,

Im using php7 but i have read it caused problems with earlier versions too (5.6+).

I based my fix based on what i read on: http://stackoverflow.com/questions/10969342/parse-error-syntax-error-unexpected-expecting-or

cheers

**Comment by abid143** [comment]
I installed woocommerce for my website..but when i placed a order it says internal server error.... please help me with this is issue...my website is notestore.co.in
phone number is :+917063413287
email id is : abidmolla241@gmail.com

**Comment by blockonomics** [comment]
@abid143 I am unable to see pay with bitcoin option on your website.
Please atttach snapshot of your settings from wp-admin, and we can help you better
you can log a ticket [here](http://blockonomics.freshdesk.com/)
