### ISSUE TITLE
Timer starts with 00:00

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/woocommerce-plugin#304]
It can be noticed for a second. Better to avoid
[Screencast from 28-12-22 03:18:33 PM IST.webm](https://user-images.githubusercontent.com/737092/209793028-8f06ff9a-3f47-4e49-9954-a6df91b068d8.webm)

**Comment by thisisayush** [comment]
This was resolved in https://github.com/blockonomics/woocommerce-plugin/commit/8484d615f200f0e9b77f681037d2b4c618866622
