### ISSUE TITLE
Couldnot generate new btc adrss

### ISSUE THREAD

**Issue by Undersidedog2** [blockonomics/woocommerce-plugin#31]
Everything was working fine but suddenly this text came over. And also callback failed warning .! Help aspa

**Comment by blockonomics** [comment]
Can you attach snapshot

**Comment by blockonomics** [comment]
Also please attach snapshot of your upgrade page https://www.blockonomics.co/blockonomics#/upgrade

**Comment by Undersidedog2** [comment]
Recieved images?

**Comment by blockonomics** [comment]
No where did you send ? Email to webmaster at blockonomics.co

**Comment by Undersidedog2** [comment]
Balance was low now i deposited btc for it. Will it fix now ?

**Comment by blockonomics** [comment]
Yes . Successive negative balance will lead to merchant getting disabled. 

After deposit (wait for confirmations). When balance become positive it will automatically start working again.
