### ISSUE TITLE
Modify filter to search single addr / txid with new custom fields

### ISSUE THREAD

**Issue by anktd** [blockonomics/woocommerce-plugin#314]
[Underpayment PR](https://github.com/blockonomics/woocommerce-plugin/pull/310) changes Custom Fields in Order Details. We can have multiple addresses & transaction ids but when this happens, they are not searchable from Filter on Order History page (image attached).

<img width="1079" alt="chrome_j5yRvzxlqZ" src="https://user-images.githubusercontent.com/97018228/222882207-d00de597-bc7c-477e-9edb-44deece29aba.png">

**Comment by shivaenigma** [comment]
Addressed in PR closing
