### ISSUE TITLE
Feature Request - Cancel Order

### ISSUE THREAD

**Issue by ryconnolly** [blockonomics/woocommerce-plugin#32]
Hi,

Thanks for the great plugin.
I'd like to suggest the following feature.  When someone cancels out of the payment page or the payment times out, it would be great if the order would cancel in woocommerce.

**Comment by blockonomics** [comment]
Thanks for the kinds words. Really appreciate !

Right now the user can go back and then retry the payment again when timeout occurs. In this case a new address is generated along with updated bitcoin price. This behaviour is very much desirable

Woocommerce actually itself cancels the orders if nothing happens on it for a long time (I have to check the time on that).

**Comment by ryconnolly** [comment]
Got it, that makes sense. Thanks!
