### ISSUE TITLE
Temp wallet issues when user has multiple stores

### ISSUE THREAD

**Issue by jusasiiv** [blockonomics/woocommerce-plugin#327]
If user has multiple stores set up, temp fund withdraw cant be made and will give error: `Error while making withdraw: You have multiple xpubs in your wallet watcher.`

Another problem with one customer having the temp fund wallet info showing even after withdraw had been made and API key is saved. Need to investigate what caused the bug

**Comment by ankit61d** [comment]
[Support ticket](https://blockonomics.freshdesk.com/a/tickets/335778) based on which this issue got surfaced. 
More info about this:
User had completed the setup more than a year ago, the checkout address is generated from their configured xpub, still the currencies tab is showing the temp wallet funds (screenshot attached).

![image](https://user-images.githubusercontent.com/97018228/236460871-197e559c-11d3-4a31-b3a6-ad817f29673a.png)

**Comment by shivaenigma** [comment]
closing as temp wallet removed
