### ISSUE TITLE
Some currencies are not working

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#329]
**Symbol translation**
Woocommerce has various symbol eg. 
![image](https://github.com/blockonomics/woocommerce-plugin/assets/22165583/74ac494c-a8ab-42b2-ac0c-a6e763d0db43)
which must be translated to our symbol [PYG](https://www.blockonomics.co/api/price?currency=PYG)
Test other currencies like YEN, YUAN in woocmmerce if they are working

**Error handling**
Currently if currencies is not supported it is failing saying *critical error occurred*. This doesn't help. It should give proper error to understand what is happening

**Comment by anktd** [comment]
Symbol translation is not required as woocommerce shortcodes and blockonomics api shortcodes are matching, thus we have support for majority of currencies. However woocommerce has more currency type than our api has support for, currently it is throwing critical error in such case. 
I have added error handling for this case to display the checkout page with specific error msg, screenshot is attached

![image](https://github.com/user-attachments/assets/f469b6f9-a17e-4397-a336-9d67ae21e93d)
