### ISSUE TITLE
Number of Confirmations and Timer

### ISSUE THREAD

**Issue by ryconnolly** [blockonomics/woocommerce-plugin#34]
Hi,

Would it be possible to add admin options to set the number of confirmations before setting order to processing and changing the timer?
For example, I'll be changing mine to 0 confirmations and 20 minutes.  However, having that as an option would be nice so it's not reverted with updates.

**Comment by blockonomics** [comment]
Interesting, others have asked for this. However, zero is not at all safe (We want to give a warning before merchant does this). Similar, very high time period is risky because price will change a lot

Implementation is straightforward. Just needs to make show necessary wanings

**Comment by ryconnolly** [comment]
I agree, warnings would be good.
In my case I've seen small payments that take well over an hour to receive first confirmation which is why I decided to switch to 0 confirmations.

**Comment by shivaenigma** [comment]
Added in [version 1.4.3](https://wordpress.org/plugins/blockonomics-bitcoin-payments/#developers)

**Comment by shivaenigma** [comment]
Closing for now. Number of confirmation option is very risky. Will be added after after having some facility on backend to analyse unconfirmed TX
