### ISSUE TITLE
PLUGIN DOESNT WORK

### ISSUE THREAD

**Issue by Undersidedog2** [blockonomics/woocommerce-plugin#36]
HELLO i have been working ur plugin already 1 months. suddenly 2 orders were cancelled (which were payd) i tried to find something in merchant logs but they are clear. and your site blockonomics.co says that sqlite3.database is locked. pls help.

**Comment by shivaenigma** [comment]
Apologies. We had a temporary issue. Thanks for reporting. Things are back to normal now. You need to manually settle those orders by looking at Address Watcher > History

Thanks again
