### ISSUE TITLE
Behaviour on Plugin Install

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/woocommerce-plugin#372]
- Bitcoin Payment method should not get enabled by default 
- It should get enabled only when APIKey is present
- On Plugin activate, show message tp user [ask to configure the plugin](https://github.com/blockonomics/woocommerce-plugin/blob/c91842875a20c452659be440c877b5344fd1b6db/blockonomics-woocommerce.php#L668)

**Comment by anktd** [comment]
This can be closed
