### ISSUE TITLE
PLUGIN DOESNT WORK AGAIN.

### ISSUE THREAD

**Issue by Undersidedog2** [blockonomics/woocommerce-plugin#38]
HELLO i have been working ur plugin already 1 months. suddenly 2 orders were cancelled (which were payd) i tried to find something in merchant logs but they are clear. and your site blockonomics.co says that sqlite3.database is locked. pls help.

**Comment by Undersidedog2** [comment]
Will be this issue frequent? I lose too much money and time :((

**Comment by blockonomics** [comment]
Hi, I am really sorry that this occcured again. We are facing scalability issues recently. 

You can find your orders in Wallet Watcher > History. There is no money lost ! All the payment would still come to your wallet

We are fixing this on urgent basis. Appreciate your patience and reporting this !
Thanks again
