### ISSUE TITLE
MERCHANT BALANCE UPDATE

### ISSUE THREAD

**Issue by Undersidedog2** [blockonomics/woocommerce-plugin#39]
I transfereed money to fill up merchant balance but no ransaction is visible ) help asap pls. I have stopped site bcs of this.. 

1JcuSLRadvJFeG7TgZDKuKUK2tbqG1efSN

**Comment by blockonomics** [comment]
Should be credited now. Thanks for the payment !

**Comment by blockonomics** [comment]
You should have got double the credits now. As gesture from our side, you can keep those .

Regards and Thanks for logging these tickets
