### ISSUE TITLE
No option for Testnet coins (Electrum)

### ISSUE THREAD

**Issue by renegenoa** [blockonomics/woocommerce-plugin#40]
Hi,

I am using Electrum 2.9.3 and trying to test out the woocommerce plugin. When I am trying to add testnet tpub to wallet watcher, it is saying invalid address. So, my question is - why is there no option to test out the service using testnet coins? Using real bitcoins for testing the service can be very expensive. Mycelium Gear allows testnet. I thought this plugin will be better than Mycelium :(

**Comment by blockonomics** [comment]
Hi,
Yes unfortunaltey, we don't have testnet right now. You can test with small amounts, the amount anyway comes straight to your wallet (you do lose tx fee if tx is confirmed) ! There is also an option in Merchants > Logs to generate test callback without spending any money

We are considered adding testnet support in few months.  Thanks for the kinds words :smirk:
