### ISSUE TITLE
Supporting litecoin or ripple

### ISSUE THREAD

**Issue by Undersidedog2** [blockonomics/woocommerce-plugin#41]
Can your plugin support recieving litecoins and ripples? and how to modify settings to recieve them. Thanks in advance.

**Comment by blockonomics** [comment]
Hi,
We don't natively support altcoins. However, you can accept LTC and ripple using our shapeshift integration. Do Blockonomics WP Settings > Accept Altcoin Payments (Using Shapeshift). 

Customer will get option on checkout to pay with Atlcoins
