### ISSUE TITLE
Shapeshift altcoins 

### ISSUE THREAD

**Issue by Undersidedog2** [blockonomics/woocommerce-plugin#42]
Hello again, i enabeld shapeshift conversions for transaction but when i load the page to buy with altocins its keepsloading for a while (my site is working on tor service) what can i do ?
![dd](https://user-images.githubusercontent.com/30299292/34039441-e0f1420e-e1a8-11e7-9b92-f1d8930889c8.PNG)

**Comment by blockonomics** [comment]
Please enable popups for your site. It should popup a shapeshit interface when you Click on _Pay With Altcoins button_

**Comment by Undersidedog2** [comment]
Okay and the next question, i have hold stock limit for 30 minutes. I have enabled auto complete transactions on 0 confirmations. How much time is needed in this way of payng ?

**Comment by blockonomics** [comment]
Unfortunately, shapeshift integration means it will convert the Altcoin to BTC and send to your BTC addresses. This will need the altcoin first to confirm and then shapeshift to exchange it. This incurs a  time of atleast 30 min - hours.

**Comment by Undersidedog2** [comment]
Its unreal to make conversation in 30 min ye? i have to increase time for blockonomics plugin and woocommerce to ? i want to know maximum time for making this convertion.

**Comment by Undersidedog2** [comment]
*convertion

**Comment by blockonomics** [comment]
I really don't know maximum time. You can ask the developers associate with [this](https://info.shapeshift.io/tools/shifty-button) Sometimes shapeshift took 2 hours. As I said, this is not a recommend way to accept altcoins, coz the integration is not native.

**Comment by Undersidedog2** [comment]
Can i change blockonomics cooldown to 2hr + timestamp to 7200 ?

**Comment by Undersidedog2** [comment]
Is this kind of change acceptable and normal ?

**Comment by blockonomics** [comment]
You mean countdown? Its really not required..The countdown can remain for 30 min or the default 10 min. It means the user has to initiate send of the altcoin tx within 30 min and the rate etc. is fixed for that timeframe. The time is taken to confirm/exchange etc. is not a factor. it can take hours/days. that is fine.

**Comment by Undersidedog2** [comment]
I asked that because, if someone pays with altcoins order won't be canceled? and blockonomics plugin wont type the error "Payment recieved after XXXXX  hours and minutes" ? bcs i have set timestamp to 1800 now. and i recieve every funds without any confirmation i have set. if status to = 0.

**Comment by blockonomics** [comment]
> I asked that because, if someone pays with altcoins order won't be canceled? and blockonomics plugin wont type the error "Payment recieved after XXXXX hours and minutes" ? bcs i have set timestamp to 1800 now. and i recieve every funds without any confirmation i have set. if status to = 0.

That code only adds a note. It doesn't change the order status to cancelled. Yes, you can change that timestamp to 1800

**Comment by Undersidedog2** [comment]
Ok, thanks for full assistance :+1:
