### ISSUE TITLE
Countdown on checkout

### ISSUE THREAD

**Issue by Undersidedog2** [blockonomics/woocommerce-plugin#44]
Hello, i have set countdown to 30 min and it was like that for a long time.
But now i checked and it is 50 min on checkout page.
In app.js its 30*60 why does thi happen ?

**Comment by Undersidedog2** [comment]
Its clearly 51 min but i have typed 30*60 in app
Timestap 1800 and etc.. everywhere i have entered 30 min but wtf.

**Comment by blockonomics** [comment]
custom times are already available. closing
