### ISSUE TITLE
Gap limit fillup takes too mich money

### ISSUE THREAD

**Issue by Undersidedog2** [blockonomics/woocommerce-plugin#48]
What is hapening? 
I deposited my balance yesterday with 200€ and now my mercant deposit is in minus 1JcuSLRadvJFeG7TgZDKuKUK2tbqG1efSN

Too much money is taken by gap limit fillup...... is it my fault? :))

**Comment by blockonomics** [comment]
Bitcoin network is full and Tx is taking lots of network fee. You seem to have lots of customer doing unpaid orders. 

We are working on a solution for this to use electrum to set customer gap limit. Will let you know an update by end of week

Thanks a lot  for understanding

**Comment by Undersidedog2** [comment]
No problem, i have texted u about issue happened while i filled up my
balance. please chekc my ticket and send me back money on addres given.
Thanks in advance and Happy new year :)

**Comment by blockonomics** [comment]
Update. Please use below facilitiy to update gap limit. Please use https://blockonomics.freshdesk.com/solution/articles/33000215760-gap-limit-faq
