### ISSUE TITLE
Help text on order confirmation page

### ISSUE THREAD

**Issue by Marow** [blockonomics/woocommerce-plugin#49]
Please add Feature that User get a Message after transaction showed in Network to his Order...

Now after i send payment it closed the countdown and transaction page on my Site but nothing more that the Transaction must be confirmed from network.

Best thing is, to add Textbox in Plugin to create Messages for "Waiting for Payment" and after Success or failed...

**Comment by blockonomics** [comment]
Can you please explain ..with a snapshot probably

**Comment by Undersidedog2** [comment]
This guy talking about notification for "USER" that his transaction is confirmed in bitcoin network. Its impossible. but possible solution is to make auto links likehttps://blockchain.info/address/BITCOIN+ADDRESS+HERE
For each order depended that all orders are based on bitcoin addreses and then are merged to orders. I think im right shiva. am not i?

**Comment by Marow** [comment]
I mean, that there must be a Text after returning the User to Order Complete Text, that the Payment is showing in Network and want Confirmations. 

And this Text can be changed in Settings for WP-Admin... Also Text in Order after Processing or like that :)

**Comment by blockonomics** [comment]
- Currenlty, It should show a Transaction ID at the bottom of the order confirmation
- TODO: Add a text saying _Order will be processed on Confirmation by the bitcoin network_
