### ISSUE TITLE
Payment confirmed but not update Woocommerce Order

### ISSUE THREAD

**Issue by Marow** [blockonomics/woocommerce-plugin#50]
Hi, 

in you Blockexplorer shows Confirmed but in my WooCommerce Orders shows "Waiting for Payment"...

Also dont find this on your site under merchants orders list or anywhere

**Comment by Marow** [comment]
I tried again. 

Have 30minutes time. Sending Transaction, after 15 changed to order-received page but Order is "Waiting for Payment"

**Comment by blockonomics** [comment]
Please check the transaction on http://blockonomics.co/ . Blockonomics requires two confirmation to mark TX as confirmed. Then your order should go in _Processing_ State. The customer should already have got order confirmation page

**Comment by Undersidedog2** [comment]
Which network are you using? TOR netowrk or worldwide ?

**Comment by Marow** [comment]
I tried again now.

Sendend payment and the Screen with the Countdown switched to Wordpress Order Complete. 
Payment in WP-Admin shows Outstanding payment

How long wait now? I see in Wallet Watcher unconfirmed now... 

But last times, after confirmed its not updating my Wordpress Orders... i am using newest Version from Wordpress Plugin List... But there is not coming "Processing" State...

In Merchant Log i dont see that the System want to send me Callback. Only see the Test Payment with 200

**Comment by Marow** [comment]
Now after much minutes Wallet Watcher shows "Partially Confirmed" 

Order Status is Outstanding Payment, nothing changed.

**Comment by Marow** [comment]
Hm i dont know why, but now its "Processing"... last times not working :) 👍

**Comment by blockonomics** [comment]
Great. Yes lets track that on the other issue
