### ISSUE TITLE
Incorrect Wallet ID's being given

### ISSUE THREAD

**Issue by ryconnolly** [blockonomics/woocommerce-plugin#51]
Hi,

It looks like the plugin has started giving incorrect wallet ID's to customers. Is there something that would cause this / a way to fix it?

**Comment by blockonomics** [comment]
Hi @ryconnolly,

All systems are working normally. Can you give an example/screenshot of what is not working for you

**Comment by ryconnolly** [comment]
Hi,

The issue seems to be intermittent.
There have been a few customers over the past few days that sent Bitcoin to the wallet ID shown, I can see in the block chain that the payments have been fully confirmed.  However they don't show up in my wallet.

**Comment by blockonomics** [comment]
- Is the payment shown in Blockonomics Wallet Watcher ?
- Which wallet are you using

**Comment by ryconnolly** [comment]
No it's not.
Using mycelium

**Comment by blockonomics** [comment]
Can you log a ticket here https://blockonomics.freshdesk.com/helpdesk/tickets with the xpub and details of the missing payments and we will get back to you there.

**Comment by blockonomics** [comment]
Closing there. Tracking in ticketing system
