### ISSUE TITLE
Shapeshift Minimum Amount

### ISSUE THREAD

**Issue by ryconnolly** [blockonomics/woocommerce-plugin#52]
Hey,

I've got a feature request.  Is it possible to add an option for a minimum $ amount to allow shapeshift?
Shapeshift has this posted on their site currently:
"PLEASE NOTE: Our Bitcoin miner fee is set very high due to Bitcoin network congestion, so please avoid small Bitcoin transactions on ShapeShift for now. Anything under $250 USD is unadvisable, and transactions may be delayed for hours."

**Comment by blockonomics** [comment]
We can also add a warning on the checkout page. Yes, the fee is very high totally agree

**Comment by blockonomics** [comment]
shapeshift wont be used anymore .. this will be shown in the newer altcoin integration
