### ISSUE TITLE
Bitcoin address field in Order

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#55]
- Bitcoin address field should also be shown for unpaid orders. This is useful for debugging
![screenshot from 2018-02-17 10-07-46](https://user-images.githubusercontent.com/22165583/36338050-46f97b12-13cb-11e8-978e-f3920c941374.png)

**Comment by jusasiiv** [comment]
Fixed here https://github.com/blockonomics/woocommerce-plugin/commit/3d4414d0ad12259f3466eaa11e35522c27de4c23
