### ISSUE TITLE
Translation files are misnamed

### ISSUE THREAD

**Issue by janhn** [blockonomics/woocommerce-plugin#60]
The names of the translation files in laguages/ don't match the plugin's textdomain. As a result, the translations are never picked up, even if present.

**Comment by shivaenigma** [comment]
Hi,
Blockonomics now uses the translations [Powered by GlotPress](https://translate.wordpress.org/projects/wp-plugins/blockonomics-bitcoin-payments), which is now standard behaviour for most plugins.

You can upload the [pot files here ](https://translate.wordpress.org/projects/wp-plugins/blockonomics-bitcoin-payments/stable/cs/default)

Let me know after that is done and I can send it to approval to the polygot community translators

The files there are misleading. I agree. We can remove the directory and just add a README pointing to https://translate.wordpress.org/projects/wp-plugins/blockonomics-bitcoin-payments/stable/cs/default

This is a desired and default behaviour now

**Comment by shivaenigma** [comment]
hi @janhn ... any thoughts... were you able to upload the translations on glot ?

**Comment by janhn** [comment]
I just updated to 1.5.1, and yes, I was able to upload the translation. But that's tangential to this issue. 
This is not about misleading links or README pointers.

It's this: the plugin's translations cannot work as it is. And so any translation effort is lost until the translation file names ("blockonomics-woocommerce") are matched with the textdomain ("blockonomics-bitcoin-payments"). Please see pull request #62.
