### ISSUE TITLE
Improve the code of the payment page for easier styling

### ISSUE THREAD

**Issue by janhn** [blockonomics/woocommerce-plugin#61]
It's a bit of a pain to style the page with [BTC] payment info. Some elements do not have classes.
Examples:

Title:
```
<div class="bnomics-bitcoin-pane" ng-hide="altcoin_waiting">
            <div>
              <h4 ng-show="order.status == -1" class="">
```
QR hint:
```
              <div class="bnomics-qr-code">
                <h5 for="btn-address">...</h5>
                <a ... </a>
                <h5> ... </h5>
```
etc.

Simply adding classes for easy addressing of these elements should help.

**Comment by shivaenigma** [comment]
Point taken. We have class 'bnomics-*,' but some tags are missing. Will get this done !

**Comment by jusasiiv** [comment]
Fixed here https://github.com/blockonomics/woocommerce-plugin/commit/3d7b6011dfa12a79865bc360e5bccec3c5e43598
