### ISSUE TITLE
User friendly installation of plugin

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#65]
## Plugin installation 

Links to settings in [plugin page](https://screenshots.firefox.com/FlWVxuCPaX81K5MH/test-wooocommerce.000webhostapp.com)

## Plugin activation message

Show a plugin [activation message](https://tommcfarlin.com/plugin-activation-message/), with link to settings page, prompting user to configure the plugin

## Settings page
Settings page should keep showing the current status of installation and prompt user to do necessary action till the plugin is in working state
  -  Installation Instructions (show always at the top of the page) : [Blog Tutorial](https://blog.blockonomics.co/how-to-accept-bitcoin-payments-on-woocommerce-using-blockonomics-f18661819a62) | [Youtube Tutorial](youtube.com/watch?v=E5nvTeuorE4)
- If no API key was just set (previously empty)
  - Show at top -  _You are few clicks away from accepting bitcoin payments_
  - Click on Get Started for Free on [Blockonomics Merchants](https://www.blockonomics.co/merchants). Complete the Wizard, and Set the APIKey when shown here

- If API Key was just set:
  - Show message at top: _Please click on Test Setup to verify Installation_

- Test Setup
This is a button that will test the current setup and show appropriate messages:
  - Will auto set callback URL if not already set. If some other callback URL already existing show link on how to integrate multiple websites
  - Test address generation using _reset_ parameter and will show errors if they exist like _fopen_ and _other errors_

## New Address Generation

- Remove address generation debug code from here and point to Settings > Blockonomics > Test Setup

**Comment by shivaenigma** [comment]
>Please click on Test Setup to verify Installation.

This should be only display when Settings is saved and APIKey has changed . For example, it is still getting display when I change the _Time period of countdown_ or just click Save without changing anything

- Move errors shown during test setup to the top shown as notices ... like we are showing _Settings saved! Please click on Test Setup to verify Installation._ . The _ Congrats !Setup Done_ is green notice and rest are _Red Notices_ 
- Align *Test Setup* button horizontal near the Save Button

**Comment by shivaenigma** [comment]
## TODO
- Test fopen error
- Test upgrade error 
- Test outgoing blocked error
