### ISSUE TITLE
Powered by blockonomics - Changes

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#66]
- Removed from checkout string
- Add to checkout  invoice page

**Comment by shivaenigma** [comment]
Little bit margin would be helpful
https://screenshots.firefox.com/MGnRWDeclmdAphhM/test-wooocommerce.000webhostapp.com

**Comment by jusasiiv** [comment]
Could it be a cache issue? Mine looks like this, also its centered: https://screenshots.firefox.com/qUv8s6e1in1WVeRg/92.222.83.165

Theme is default Twenty Seventeen

**Comment by shivaenigma** [comment]
Yes. Looks like a cache issue
