### ISSUE TITLE
Minification/Size Issues

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#71]
- Currently doesn't work along with  minification plugin
- Lots of http requests are sent to load files and is taking time

Try to make it work with minifiers or combine all JS into one file

**Comment by shivaenigma** [comment]
- Increasing priority of this. Try to decrease number of files/size

**Comment by shivaenigma** [comment]
- Also remove unused files. It is unnecessary increasing plugin size

**Comment by shivaenigma** [comment]
- Also remove unused files. It is uncessary increasing plugin size

**Comment by blockonomics** [comment]
People are reporting it is taking 15 seconds to load. We need to check stats on a medium speed connection

**Comment by DarrenWestwood** [comment]
[JavaScript Speed Report - Blockonomics WooCommerce.docx](https://github.com/blockonomics/woocommerce-plugin/files/3152140/JavaScript.Speed.Report.-.Blockonomics.WooCommerce.docx)

Areas to improve:
* reduce load times - minify angular-qrcode.js
* reduce non-blocking resource loads - async param when using enqueue scripts

**Comment by DarrenWestwood** [comment]
Non-blocking resource load times have been reduced using defer instead of async to maintain working functionality.
