### ISSUE TITLE
checkout description field is missing

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#74]
- Some merchants want to put some text in the description checkout field
- Leave it as default empty

![blockonomics-checkout-description](https://user-images.githubusercontent.com/22165583/45914199-27944880-be5f-11e8-846b-c89eef3a9d4e.png)
![blockonomics-wc-settings](https://user-images.githubusercontent.com/22165583/45914200-282cdf00-be5f-11e8-951b-385fb3f05207.png)

**Comment by DarrenWestwood** [comment]
![description field](https://user-images.githubusercontent.com/39666372/46736538-9237e780-cc99-11e8-9460-f51ae39308eb.png)
