### ISSUE TITLE
Factor tx fee / Underpayment Slack

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/woocommerce-plugin#76]
- Some customer send BTC from their exchanges
- In this case the received amount will be actual amount - btc tx fee
- Give option to admin to accept such orders
- Have to handle boundary cases like if order amount itself is 1USD, we cannot accept such payments
- Can also Allow for slack in underpaid order with a fix percentage

**Comment by shivaenigma** [comment]
Lets add a new config option
- _Underpayment Slack % (Accept payment amounts which off by a small percent)_
- Min value 0, Max value 10

**Comment by shivaenigma** [comment]
A clarification here. We don't need a factor tx fee setting, Please remove that. Only Underpayment slack is enough
