### ISSUE TITLE
Payment Screen breaking site

### ISSUE THREAD

**Issue by PoeNedge** [blockonomics/woocommerce-plugin#9]
Hi, great plugin, works great, but on the payments screen there seems to be a conflict with Visual Composer.

See here:

[http://imgur.com/iiQGAqg](here)

**Comment by blockonomics** [comment]
Thanks for reporting. Can you help in steps to reproduce  (how to install and configure Visual composer)

**Comment by blockonomics** [comment]
@PoeNedge  ping

**Comment by ryconnolly** [comment]
I have found the same issue.
Using the Porto Wordpress theme which includes Visual Composer (https://codecanyon.net/item/visual-composer-page-builder-for-wordpress/242431)
Visual composer works out of the box with the theme so I didn't need to configure anything.   It seems on the blockonomics payment page the visual composer elements in the footer are broken.

**Comment by blockonomics** [comment]
Thanks for logging. Starting work on this

**Comment by aleangel1212** [comment]
@ryconnolly, could you post some screenshots of the issue appearing on the Porto theme? I am unable to replicate it.

**Comment by ryconnolly** [comment]
Hi,
Here is a screenshot of the payment page.  You can see the issue in the footer.
https://puu.sh/yt6MV/68525e30a6.png

**Comment by aleangel1212** [comment]
@ryconnolly I am still unable to reproduce the issue. Could you give me a link to your source code or  point me to a live instance of the site so that I can determine what the problem is?

**Comment by aleangel1212** [comment]
@ryconnolly you can also send me an email at alevecchi@blockonomics.co with the credentials to your website and I can take a look at it that way

**Comment by pullout** [comment]
Mywebsite does same thing

**Comment by pullout** [comment]
I got everything working. It didnt really work with my Theme "Pheremone" But i had to get rid of an overlay positioning from the theme. Got it working. But now if i go to use visual composer it just shows a really shitty copy of the pay screen with an "unecure connection" doohocky.

**Comment by pullout** [comment]
have to refresh it

**Comment by DarrenWestwood** [comment]
[Issue #9 - Report.pdf](https://github.com/blockonomics/woocommerce-plugin/files/3197756/Issue.9.-.Report.pdf)

Solution:
* Implement custom post type to display checkout pages
